### ISSUE TITLE
simple selector support?

### ISSUE THREAD

**Issue by futurist** [j2css/j2c#10]
like below code that every one may have in a normal css file:
````
j2c.sheet({
    "body": {color: "#33e" }, "p":{margin:0}
})
````
but don't compile right, is this an issue? or it's not the right way to use j2c?

**Comment by futurist** [comment]
sorry just found the docs mentioned the problem:

>Element selectors like p or body match the property pattern and must thus be preceded by a space.

so, j2c IMO is the best for practical and flexible

**Comment by futurist** [comment]
but found 
````
j2c.sheet({
    ":global(body)": {color: "#33e" }
})
````
cannot compiled correctly

**Comment by futurist** [comment]
````
j2c.sheet({" div": j2c.inline({"*zoom":1}) })
````

above will produce: 
````
div{
*zoom:1;;
}
````
which will produce 2 comas

**Comment by pygy** [comment]
Hello @futurist, thanks for the praise and the report :-)

so far, `:global` only works with class and animation names. At this point, elements names and ids are never localized.

The two semi-columns are indeed sub-optimal, however, it will not IIRC be misparsed by CSS engines. For the odd case where you need a CSS hack, you can also directly use a string to represent the key/value pair:

```JS
j2c.sheet({" div": "*zoom:1"})
```

It's what happens under the hood when using `j2c.inline` as you did. Since both `j2c.inline` and `j2c.sheet` add semi-columns, you end up with both.

If you need more than one property, as it is often the case, you can use an array:

```JS
j2c.sheet({" div": [
    "*zoom:1",
    {height$width:"200px", color:"#f00"}
]})
```

**Comment by futurist** [comment]
is any tool / code to convert existing CSS file into j2c module?

**Comment by pygy** [comment]
Not at this time... 

It's been requested several times, though.

I'll give it a crack as soon as I can (looking into suitable deps right now).

**Comment by barneycarroll** [comment]
@pygy you may be interested in PostCSS. It seems to have established itself as the go-to tool for CSS AST parsing and transpilation. I have seen PostCSS plugins used to consume CSS and produce output supplemented by JSON, which would seem to be a good first step for this…

**Comment by pygy** [comment]
Good suggestion. I was looking into https://github.com/reworkcss/css, but
postcss may be a better option, since it supports many things besides pure
CSS...

The output of postcss-js is almost exactly what we need (the `"div"` to `"
div"` conversion is necessary, but AFAICT, that's all...

—Pierre-Yves

**Comment by pygy** [comment]
Closing for now, since, AFAICT we covered the initial topic. See #12 for to get updates on the importer.

**Comment by pygy** [comment]
FWIW, since v0.10, you can use element selectors at the top level without initial spaces.
