### ISSUE TITLE
inherit style property from other selector

### ISSUE THREAD

**Issue by futurist** [j2css/j2c#13]
when there's a form element, which want to inherit style property from other selector, maybe below?
````
{
  '.form_div':{
    font_size:'18px', color:'red'
  },
  '.form_div input':{
    '@select(.form_div)': ['font_size']    //now input has {font_size:'18px'}
  }
}
````
like inherit, but can select which property to apply to input
Is that possible? or any better way to do this?

**Comment by pygy** [comment]
You can use `font_size: 'inherit'` in this case: https://jsfiddle.net/rgfcfywc/

In a scenario where you couldn't take advantage of the CSS cascade, you could factor out the properties you want to share and pass them as a mixin:

```JS
var commonProperties = {font_size: '18px'} // pick less generic name for your use case

var sheet = j2c.sheet({
  '.form_div': [
    commonProperties,
    {color: 'red'},
  ' input': {
    commonProperties,
  }
}
```

You can override the properties of the mixin by putting them in an object that follows the mixin in the array.

It would be very hard to implement your suggestion on top of the current architecture (especially because of nested selectors and conditional at rules).

**Comment by pygy** [comment]
Alternatively, if you're only using classes, you can use `@extend`, then override the styles you don't want inherited.
