### ISSUE TITLE
How to manage grids?

### ISSUE THREAD

**Issue by dontwork** [j2css/j2c#7]
If everything in a project is componentized - how should one manage a grid layout using j2c?

**Comment by pygy** [comment]
Sorry for the delay...

It really depends on what you're writing, and what grid system you want to use and what you want to use it system for. Could you give me more details on what you want to do?

In general, regarding grids, I'm partial to [PocketGrid](https://github.com/arnaudleray/pocketgrid), which I've ported to some extent to earlier versions of j2c. I'd have to rethink how best to port it to v0.8...

It leaves it up to you to define the grid items widths and gutters using CSS (rather than coming with pre-defined `.col-4` classes), which makes it unique among grid systems AFAIK, but enables both its small size and great versatility (check the feature list). Its [documentation](http://arnaudleray.github.io/pocketgrid/docs/) is very good.

**Comment by pygy** [comment]
@dontwork check this out :-) https://github.com/j2css/j2c-pocketgrid
